openapi: 3.2.0
info:
  title: 3gpp-grp-pp Group Parameters Provisioning (Collection) API
  version: 1.1.0
  description: "API for Group Parameters Provisioning.  \n© 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
servers:
- url: '{apiRoot}/3gpp-grp-pp/v1'
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 5.2.4 of 3GPP TS 29.122.
security:
- {}
- oAuth2ClientCredentials: []
tags:
- name: Group Parameters Provisioning (Collection)
paths:
  /pp:
    post:
      summary: Request the creation of a new Group Parameters Provisioning.
      tags:
      - Group Parameters Provisioning (Collection)
      operationId: CreateGrpParamsProvisioning
      requestBody:
        description: 'Representation of the new Group Parameters Provisioning to be created at the NEF.

          '
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrpPpData'
      responses:
        '201':
          description: 'Created. A representation of the created Individual Group Parameters Provisioning resource is returned in the response body.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GrpPpData'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource, according to the structure {apiRoot}/3gpp-grp-pp/v1/pp/{ppId}

                '
              required: true
              schema:
                type: string
        '400':
          $ref: TS29122_CommonData.yaml#/components/responses/400
        '401':
          $ref: TS29122_CommonData.yaml#/components/responses/401
        '403':
          $ref: TS29122_CommonData.yaml#/components/responses/403
        '404':
          $ref: TS29122_CommonData.yaml#/components/responses/404
        '411':
          $ref: TS29122_CommonData.yaml#/components/responses/411
        '413':
          $ref: TS29122_CommonData.yaml#/components/responses/413
        '415':
          $ref: TS29122_CommonData.yaml#/components/responses/415
        '429':
          $ref: TS29122_CommonData.yaml#/components/responses/429
        '500':
          $ref: TS29122_CommonData.yaml#/components/responses/500
        '503':
          $ref: TS29122_CommonData.yaml#/components/responses/503
        default:
          $ref: TS29122_CommonData.yaml#/components/responses/default
components:
  schemas:
    GrpPpData:
      description: Represents the Group Parameters Provisioning data.
      type: object
      properties:
        afId:
          type: string
        mtcProviderId:
          $ref: TS29571_CommonData.yaml#/components/schemas/MtcProviderInformation
        dnnSnssaiGrpData:
          $ref: '#/components/schemas/DnnSnssaiGrpData'
        suppFeat:
          $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
      required:
      - afId
    DnnSnssaiGrpData:
      description: Represents DNN and S-NSSAI specific Group Parameters data.
      type: object
      properties:
        extGroupId:
          $ref: TS29122_CommonData.yaml#/components/schemas/ExternalGroupId
        dnn:
          $ref: TS29571_CommonData.yaml#/components/schemas/Dnn
        snssai:
          $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
        defQos:
          $ref: '#/components/schemas/AfReqDefaultQoS'
        ladnServArea:
          $ref: '#/components/schemas/LadnServArea'
      required:
      - extGroupId
      - dnn
      - snssai
      anyOf:
      - required:
        - defQos
      - required:
        - ladnServArea
    AfReqDefaultQoS:
      description: Represents the AF requested default QoS.
      type: object
      properties:
        5qi:
          $ref: TS29571_CommonData.yaml#/components/schemas/5Qi
        arp:
          $ref: TS29571_CommonData.yaml#/components/schemas/Arp
        priorityLevel:
          $ref: TS29571_CommonData.yaml#/components/schemas/5QiPriorityLevelRm
      required:
      - 5qi
      - arp
    LadnServArea:
      description: Represents an LADN Service Area.
      type: object
      properties:
        geographicAreas:
          type: array
          items:
            $ref: TS29572_Nlmf_Location.yaml#/components/schemas/GeographicArea
          minItems: 1
        civicAddresses:
          type: array
          items:
            $ref: TS29572_Nlmf_Location.yaml#/components/schemas/CivicAddress
          minItems: 1
        tais:
          type: array
          items:
            $ref: TS29571_CommonData.yaml#/components/schemas/Tai
          minItems: 1
      oneOf:
      - required:
        - geographicAreas
      - required:
        - civicAddresses
      - required:
        - tais
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}
externalDocs:
  description: '3GPP TS 29.522 V19.5.0; 5G System; Network Exposure Function Northbound APIs.

    '
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.522/
