openapi: 3.2.0
info:
  title: 3gpp-acs-pp Individual ACS Configuration Subscription API
  version: 1.1.2
  description: "API for 5G ACS Parameter Provision.  \n© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
servers:
- url: '{apiRoot}/3gpp-acs-pp/v1'
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 5.2.4 of 3GPP TS 29.122.
security:
- {}
- oAuth2ClientCredentials: []
tags:
- name: Individual ACS Configuration Subscription
paths:
  /{afId}/subscriptions/{subscriptionId}:
    get:
      summary: read an active subscription for the AF and the subscription Id
      operationId: ReadAnSubscription
      tags:
      - Individual ACS Configuration Subscription
      parameters:
      - name: afId
        in: path
        description: Identifier of the AF
        required: true
        schema:
          type: string
      - name: subscriptionId
        in: path
        description: Identifier of the subscription resource
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK (Successful get the active subscription)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcsConfigurationData'
        '307':
          $ref: TS29122_CommonData.yaml#/components/responses/307
        '308':
          $ref: TS29122_CommonData.yaml#/components/responses/308
        '400':
          $ref: TS29122_CommonData.yaml#/components/responses/400
        '401':
          $ref: TS29122_CommonData.yaml#/components/responses/401
        '403':
          $ref: TS29122_CommonData.yaml#/components/responses/403
        '404':
          $ref: TS29122_CommonData.yaml#/components/responses/404
        '406':
          $ref: TS29122_CommonData.yaml#/components/responses/406
        '429':
          $ref: TS29122_CommonData.yaml#/components/responses/429
        '500':
          $ref: TS29122_CommonData.yaml#/components/responses/500
        '503':
          $ref: TS29122_CommonData.yaml#/components/responses/503
        default:
          $ref: TS29122_CommonData.yaml#/components/responses/default
    put:
      summary: Fully updates/replaces an existing subscription resource
      operationId: FullyUpdateAnSubscription
      tags:
      - Individual ACS Configuration Subscription
      parameters:
      - name: afId
        in: path
        description: Identifier of the AF
        required: true
        schema:
          type: string
      - name: subscriptionId
        in: path
        description: Identifier of the subscription resource
        required: true
        schema:
          type: string
      requestBody:
        description: Parameters to update/replace the existing subscription
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcsConfigurationData'
      responses:
        '200':
          description: OK (Successful update of the existing subscription)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcsConfigurationData'
        '204':
          description: 'Successful case. The resource has been successfully updated and no additional content is to be sent in the response message.

            '
        '307':
          $ref: TS29122_CommonData.yaml#/components/responses/307
        '308':
          $ref: TS29122_CommonData.yaml#/components/responses/308
        '400':
          $ref: TS29122_CommonData.yaml#/components/responses/400
        '401':
          $ref: TS29122_CommonData.yaml#/components/responses/401
        '403':
          $ref: TS29122_CommonData.yaml#/components/responses/403
        '404':
          $ref: TS29122_CommonData.yaml#/components/responses/404
        '411':
          $ref: TS29122_CommonData.yaml#/components/responses/411
        '413':
          $ref: TS29122_CommonData.yaml#/components/responses/413
        '415':
          $ref: TS29122_CommonData.yaml#/components/responses/415
        '429':
          $ref: TS29122_CommonData.yaml#/components/responses/429
        '500':
          $ref: TS29122_CommonData.yaml#/components/responses/500
        '503':
          $ref: TS29122_CommonData.yaml#/components/responses/503
        default:
          $ref: TS29122_CommonData.yaml#/components/responses/default
    patch:
      summary: Partial modifies an existing subscription resource.
      operationId: PartialUpdateAnSubscription
      tags:
      - Individual ACS Configuration Subscription
      parameters:
      - name: afId
        in: path
        description: Identifier of the AF
        required: true
        schema:
          type: string
      - name: subscriptionId
        in: path
        description: Identifier of the subscription resource
        required: true
        schema:
          type: string
      requestBody:
        description: Parameters to modify the existing subscription.
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/AcsConfigurationDataPatch'
      responses:
        '200':
          description: 'OK. The subscription resource was successfully modified and a representation of the  updated resource is returned.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcsConfigurationData'
        '204':
          description: 'No Content. The resource has been successfully modified and no additional content is to  be sent in the response message.

            '
        '307':
          $ref: TS29122_CommonData.yaml#/components/responses/307
        '308':
          $ref: TS29122_CommonData.yaml#/components/responses/308
        '400':
          $ref: TS29122_CommonData.yaml#/components/responses/400
        '401':
          $ref: TS29122_CommonData.yaml#/components/responses/401
        '403':
          $ref: TS29122_CommonData.yaml#/components/responses/403
        '404':
          $ref: TS29122_CommonData.yaml#/components/responses/404
        '411':
          $ref: TS29122_CommonData.yaml#/components/responses/411
        '413':
          $ref: TS29122_CommonData.yaml#/components/responses/413
        '415':
          $ref: TS29122_CommonData.yaml#/components/responses/415
        '429':
          $ref: TS29122_CommonData.yaml#/components/responses/429
        '500':
          $ref: TS29122_CommonData.yaml#/components/responses/500
        '503':
          $ref: TS29122_CommonData.yaml#/components/responses/503
        default:
          $ref: TS29122_CommonData.yaml#/components/responses/default
    delete:
      summary: Deletes an already existing subscription
      operationId: DeleteAnSubscription
      tags:
      - Individual ACS Configuration Subscription
      parameters:
      - name: afId
        in: path
        description: Identifier of the AF
        required: true
        schema:
          type: string
      - name: subscriptionId
        in: path
        description: Identifier of the subscription resource
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content (Successful deletion of the existing subscription)
        '307':
          $ref: TS29122_CommonData.yaml#/components/responses/307
        '308':
          $ref: TS29122_CommonData.yaml#/components/responses/308
        '400':
          $ref: TS29122_CommonData.yaml#/components/responses/400
        '401':
          $ref: TS29122_CommonData.yaml#/components/responses/401
        '403':
          $ref: TS29122_CommonData.yaml#/components/responses/403
        '404':
          $ref: TS29122_CommonData.yaml#/components/responses/404
        '429':
          $ref: TS29122_CommonData.yaml#/components/responses/429
        '500':
          $ref: TS29122_CommonData.yaml#/components/responses/500
        '503':
          $ref: TS29122_CommonData.yaml#/components/responses/503
        default:
          $ref: TS29122_CommonData.yaml#/components/responses/default
components:
  schemas:
    AcsConfigurationData:
      description: Represents an individual ACS Configuration subscription resource.
      type: object
      properties:
        self:
          $ref: TS29122_CommonData.yaml#/components/schemas/Link
        exterGroupId:
          $ref: TS29122_CommonData.yaml#/components/schemas/ExternalGroupId
        gpsi:
          $ref: TS29571_CommonData.yaml#/components/schemas/Gpsi
        acsInfo:
          $ref: TS29571_CommonData.yaml#/components/schemas/AcsInfo
        mtcProviderId:
          $ref: TS29571_CommonData.yaml#/components/schemas/MtcProviderInformation
        suppFeat:
          $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
      required:
      - acsInfo
      - suppFeat
    AcsConfigurationDataPatch:
      description: 'Represents the parameters to request to modify an existing Individual ACS Configuration subscription resource.

        '
      type: object
      properties:
        acsInfo:
          $ref: TS29571_CommonData.yaml#/components/schemas/AcsInfo
        mtcProviderId:
          $ref: TS29571_CommonData.yaml#/components/schemas/MtcProviderInformation
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}
externalDocs:
  description: '3GPP TS 29.522 V17.8.0; 5G System; Network Exposure Function Northbound APIs.

    '
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.522/
