openapi: 3.2.0
info:
  title: File Data Reporting MnS Files API
  version: 19.1.0
  description: OAS 3.0.1 definition of the File Data Reporting MnS © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
servers:
- url: '{MnSRoot}/fileDataReportingMnS/{MnSVersion}'
  variables:
    MnSRoot:
      description: See clause 4.4.3 of TS 32.158
      default: http://example.com/3GPPManagement
    MnSVersion:
      description: Version number of the OpenAPI definition
      default: XXX
tags:
- name: Files
paths:
  /files:
    get:
      summary: Read information about available files
      description: Information about available files is read with HTTP GET. The files for which information shall be returned are identified with the path component (base resource) and the query component (fileDataType, beginTime, endTime) of the URI.
      parameters:
      - name: fileDataType
        in: query
        description: This parameter selects files based on the file data type.
        required: true
        schema:
          $ref: '#/components/schemas/FileDataType'
      - name: beginTime
        in: query
        description: This parameter selects files based on the earliest time they became available
        required: false
        schema:
          $ref: TS28623_ComDefs.yaml#/components/schemas/DateTime
      - name: endTime
        in: query
        description: This parameter selects files based on the latest time they became available
        required: false
        schema:
          $ref: TS28623_ComDefs.yaml#/components/schemas/DateTime
      responses:
        '200':
          description: '''Success case ("200 OK"). The resources identified in the request for retrieval are returned in the response message body.'''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FileInfo'
        default:
          description: Error case.
          content:
            application/json:
              schema:
                $ref: TS28623_ComDefs.yaml#/components/schemas/ErrorResponse
      tags:
      - Files
components:
  schemas:
    FileDataType:
      type: string
      enum:
      - Performance
      - Trace
      - Analytics
      - Proprietary
    FileInfo:
      type: object
      properties:
        fileLocation:
          $ref: TS28623_ComDefs.yaml#/components/schemas/Uri
        fileSize:
          type: integer
        fileReadyTime:
          $ref: TS28623_ComDefs.yaml#/components/schemas/DateTime
        fileExpirationTime:
          $ref: TS28623_ComDefs.yaml#/components/schemas/DateTime
        fileCompression:
          type: string
        fileFormat:
          type: string
        fileDataType:
          $ref: '#/components/schemas/FileDataType'
        jobId:
          type: string
externalDocs:
  description: 3GPP TS 28.532; Generic management services
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.532/
