openapi: 3.2.0
info:
  title: Npcf_PolicyAuthorization Service PCSCF Restoration Indication API
  version: 1.1.5
  description: 'PCF Policy Authorization Service.

    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).

    All rights reserved.

    '
servers:
- url: '{apiRoot}/npcf-policyauthorization/v1'
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501
security:
- {}
- oAuth2ClientCredentials:
  - npcf-policyauthorization
tags:
- name: PCSCF Restoration Indication
paths:
  /app-sessions/pcscf-restoration:
    post:
      summary: Indicates P-CSCF restoration and does not create an Individual Application Session Context
      operationId: PcscfRestoration
      tags:
      - PCSCF Restoration Indication
      requestBody:
        description: PCSCF Restoration Indication
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PcscfRestorationRequestData'
      responses:
        '204':
          description: The deletion is confirmed without returning additional data.
        '307':
          $ref: TS29571_CommonData.yaml#/components/responses/307
        '308':
          $ref: TS29571_CommonData.yaml#/components/responses/308
        '400':
          $ref: TS29571_CommonData.yaml#/components/responses/400
        '401':
          $ref: TS29571_CommonData.yaml#/components/responses/401
        '403':
          $ref: TS29571_CommonData.yaml#/components/responses/403
        '404':
          $ref: TS29571_CommonData.yaml#/components/responses/404
        '411':
          $ref: TS29571_CommonData.yaml#/components/responses/411
        '413':
          $ref: TS29571_CommonData.yaml#/components/responses/413
        '415':
          $ref: TS29571_CommonData.yaml#/components/responses/415
        '429':
          $ref: TS29571_CommonData.yaml#/components/responses/429
        '500':
          $ref: TS29571_CommonData.yaml#/components/responses/500
        '503':
          $ref: TS29571_CommonData.yaml#/components/responses/503
        default:
          $ref: TS29571_CommonData.yaml#/components/responses/default
components:
  schemas:
    PcscfRestorationRequestData:
      description: Indicates P-CSCF restoration.
      type: object
      oneOf:
      - required:
        - ueIpv4
      - required:
        - ueIpv6
      properties:
        dnn:
          $ref: TS29571_CommonData.yaml#/components/schemas/Dnn
        ipDomain:
          type: string
        sliceInfo:
          $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
        supi:
          $ref: TS29571_CommonData.yaml#/components/schemas/Supi
        ueIpv4:
          $ref: TS29571_CommonData.yaml#/components/schemas/Ipv4Addr
        ueIpv6:
          $ref: TS29571_CommonData.yaml#/components/schemas/Ipv6Addr
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            npcf-policyauthorization: Access to the Npcf_PolicyAuthorization API
externalDocs:
  description: 3GPP TS 29.514 V16.10.0; 5G System; Policy Authorization Service;Stage 3.
  url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.514/
