openapi: 3.2.0
info:
  title: 3gpp-ueid UE ID Mapping Information Provisioning (Collection) API
  version: 1.2.0
  description: "API for UE ID service.\n© 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
servers:
- url: '{apiRoot}/3gpp-ueid/v1'
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 5.2.4 of 3GPP TS 29.122.
security:
- {}
- oAuth2ClientCredentials: []
tags:
- name: UE ID Mapping Information Provisioning (Collection)
paths:
  /{afId}/pp:
    parameters:
    - name: afId
      in: path
      description: Represents the identifier of the AF.
      required: true
      schema:
        type: string
    post:
      summary: Request the creation of a new UE ID Mapping Information Provisioning.
      operationId: CreateUeIdMappingProvisioning
      tags:
      - UE ID Mapping Information Provisioning (Collection)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UeIdMappingInfo'
      responses:
        '201':
          description: 'Created. A representation of the created Individual UE ID Mapping Information Provisioning resource is returned in the response body.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UeIdMappingInfo'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource.

                '
              required: true
              schema:
                type: string
        '400':
          $ref: TS29122_CommonData.yaml#/components/responses/400
        '401':
          $ref: TS29122_CommonData.yaml#/components/responses/401
        '403':
          $ref: TS29122_CommonData.yaml#/components/responses/403
        '404':
          $ref: TS29122_CommonData.yaml#/components/responses/404
        '411':
          $ref: TS29122_CommonData.yaml#/components/responses/411
        '413':
          $ref: TS29122_CommonData.yaml#/components/responses/413
        '415':
          $ref: TS29122_CommonData.yaml#/components/responses/415
        '429':
          $ref: TS29122_CommonData.yaml#/components/responses/429
        '500':
          $ref: TS29122_CommonData.yaml#/components/responses/500
        '503':
          $ref: TS29122_CommonData.yaml#/components/responses/503
        default:
          $ref: TS29122_CommonData.yaml#/components/responses/default
components:
  schemas:
    UeIdMappingInfo:
      description: 'Represents the UE ID Mapping Information Provisioning.

        '
      type: object
      properties:
        rsUeIdMappingInfo:
          $ref: '#/components/schemas/RangSlUeIdMappInfo'
        suppFeat:
          $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
    RangSlUeIdMappInfo:
      description: 'Represents the Ranging/Sidelink UE ID mapping information between the Application Layer ID and the GPSI.

        '
      type: object
      properties:
        appLayerId:
          $ref: TS29571_CommonData.yaml#/components/schemas/ApplicationlayerId
        gpsi:
          $ref: TS29571_CommonData.yaml#/components/schemas/Gpsi
      required:
      - appLayerId
      - gpsi
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}
externalDocs:
  description: 3GPP TS 29.522 V19.5.0; 5G System; Network Exposure Function Northbound APIs.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.522/
